import {
	STRUCTURE_RAMPART, STRUCTURE_TOWER,
	STRUCTURE_CONTAINER, STRUCTURE_ROAD,
} from '../index.js';

// Canonical stronghold deployment layouts. When a deploying invader core
// (deployTime <= gameTime + 1) is processed, the engine reads
// `core.templateName` and places the listed structures relative to the core
// position. The invader core itself stays in place; the entries with type
// STRUCTURE_INVADER_CORE in the canonical source are skipped during deploy
// (engine/processor/intents/invader-core/stronghold/stronghold.js:100).
//
// The same tile commonly carries a road + rampart, or a container + road +
// rampart — duplicates by (type, dx, dy) within a template are an error in
// the canonical source, but multiple distinct types on the same tile are
// expected.
//
// Source: @screeps/common/lib/strongholds.js
export interface StrongholdStructureEntry {
	readonly type: string;
	readonly dx: number;
	readonly dy: number;
}

export interface StrongholdTemplate {
	readonly name: string;
	readonly rewardLevel: number;
	readonly coreLevel: number;
	/** Structures placed by deployStronghold, relative to core (dx, dy).
	 *  Excludes the invader-core entry itself. */
	readonly structures: ReadonlyArray<StrongholdStructureEntry>;
}

const bunker1: StrongholdTemplate = {
	name: 'bunker1',
	rewardLevel: 1,
	coreLevel: 1,
	structures: [
		{ type: STRUCTURE_RAMPART,   dx:  0, dy:  0 },
		{ type: STRUCTURE_RAMPART,   dx:  1, dy:  1 },
		{ type: STRUCTURE_TOWER,     dx:  1, dy:  1 },
		{ type: STRUCTURE_ROAD,      dx:  0, dy:  1 },
		{ type: STRUCTURE_RAMPART,   dx:  0, dy:  1 },
		{ type: STRUCTURE_CONTAINER, dx:  1, dy:  0 },
		{ type: STRUCTURE_ROAD,      dx:  1, dy:  0 },
		{ type: STRUCTURE_RAMPART,   dx:  1, dy:  0 },
	],
};

const bunker2: StrongholdTemplate = {
	name: 'bunker2',
	rewardLevel: 2,
	coreLevel: 2,
	structures: [
		{ type: STRUCTURE_RAMPART,   dx:  0, dy:  0 },
		{ type: STRUCTURE_TOWER,     dx:  1, dy:  1 },
		{ type: STRUCTURE_RAMPART,   dx:  1, dy:  1 },
		{ type: STRUCTURE_TOWER,     dx: -1, dy: -1 },
		{ type: STRUCTURE_RAMPART,   dx: -1, dy: -1 },
		{ type: STRUCTURE_ROAD,      dx:  0, dy: -1 },
		{ type: STRUCTURE_RAMPART,   dx:  0, dy: -1 },
		{ type: STRUCTURE_ROAD,      dx:  1, dy: -1 },
		{ type: STRUCTURE_RAMPART,   dx:  1, dy: -1 },
		{ type: STRUCTURE_ROAD,      dx: -1, dy:  1 },
		{ type: STRUCTURE_RAMPART,   dx: -1, dy:  1 },
		{ type: STRUCTURE_ROAD,      dx:  0, dy:  1 },
		{ type: STRUCTURE_RAMPART,   dx:  0, dy:  1 },
		{ type: STRUCTURE_CONTAINER, dx:  1, dy:  0 },
		{ type: STRUCTURE_ROAD,      dx:  1, dy:  0 },
		{ type: STRUCTURE_RAMPART,   dx:  1, dy:  0 },
		{ type: STRUCTURE_CONTAINER, dx: -1, dy:  0 },
		{ type: STRUCTURE_ROAD,      dx: -1, dy:  0 },
		{ type: STRUCTURE_RAMPART,   dx: -1, dy:  0 },
	],
};

const bunker3: StrongholdTemplate = {
	name: 'bunker3',
	rewardLevel: 3,
	coreLevel: 3,
	structures: [
		{ type: STRUCTURE_RAMPART,   dx:  0, dy:  0 },
		{ type: STRUCTURE_TOWER,     dx:  1, dy:  1 },
		{ type: STRUCTURE_RAMPART,   dx:  1, dy:  1 },
		{ type: STRUCTURE_TOWER,     dx: -1, dy: -1 },
		{ type: STRUCTURE_RAMPART,   dx: -1, dy: -1 },
		{ type: STRUCTURE_TOWER,     dx: -1, dy:  1 },
		{ type: STRUCTURE_RAMPART,   dx: -1, dy:  1 },
		{ type: STRUCTURE_ROAD,      dx: -2, dy: -1 },
		{ type: STRUCTURE_RAMPART,   dx: -2, dy: -1 },
		{ type: STRUCTURE_ROAD,      dx:  0, dy: -1 },
		{ type: STRUCTURE_RAMPART,   dx:  0, dy: -1 },
		{ type: STRUCTURE_ROAD,      dx: -1, dy:  0 },
		{ type: STRUCTURE_RAMPART,   dx: -1, dy:  0 },
		{ type: STRUCTURE_ROAD,      dx:  1, dy:  0 },
		{ type: STRUCTURE_RAMPART,   dx:  1, dy:  0 },
		{ type: STRUCTURE_ROAD,      dx: -2, dy:  1 },
		{ type: STRUCTURE_RAMPART,   dx: -2, dy:  1 },
		{ type: STRUCTURE_ROAD,      dx:  0, dy:  1 },
		{ type: STRUCTURE_RAMPART,   dx:  0, dy:  1 },
		{ type: STRUCTURE_ROAD,      dx: -2, dy:  2 },
		{ type: STRUCTURE_RAMPART,   dx: -2, dy:  2 },
		{ type: STRUCTURE_ROAD,      dx: -1, dy:  2 },
		{ type: STRUCTURE_RAMPART,   dx: -1, dy:  2 },
		{ type: STRUCTURE_ROAD,      dx:  1, dy:  2 },
		{ type: STRUCTURE_RAMPART,   dx:  1, dy:  2 },
		{ type: STRUCTURE_CONTAINER, dx:  1, dy: -1 },
		{ type: STRUCTURE_ROAD,      dx:  1, dy: -1 },
		{ type: STRUCTURE_RAMPART,   dx:  1, dy: -1 },
		{ type: STRUCTURE_CONTAINER, dx: -2, dy:  0 },
		{ type: STRUCTURE_ROAD,      dx: -2, dy:  0 },
		{ type: STRUCTURE_RAMPART,   dx: -2, dy:  0 },
		{ type: STRUCTURE_CONTAINER, dx:  0, dy:  2 },
		{ type: STRUCTURE_ROAD,      dx:  0, dy:  2 },
		{ type: STRUCTURE_RAMPART,   dx:  0, dy:  2 },
	],
};

const bunker4: StrongholdTemplate = {
	name: 'bunker4',
	rewardLevel: 4,
	coreLevel: 4,
	structures: [
		{ type: STRUCTURE_RAMPART,   dx:  0, dy:  0 },
		{ type: STRUCTURE_TOWER,     dx:  1, dy:  1 },
		{ type: STRUCTURE_RAMPART,   dx:  1, dy:  1 },
		{ type: STRUCTURE_TOWER,     dx: -1, dy: -1 },
		{ type: STRUCTURE_RAMPART,   dx: -1, dy: -1 },
		{ type: STRUCTURE_TOWER,     dx: -1, dy:  1 },
		{ type: STRUCTURE_RAMPART,   dx: -1, dy:  1 },
		{ type: STRUCTURE_TOWER,     dx:  1, dy: -1 },
		{ type: STRUCTURE_RAMPART,   dx:  1, dy: -1 },
		{ type: STRUCTURE_ROAD,      dx: -2, dy: -2 },
		{ type: STRUCTURE_RAMPART,   dx: -2, dy: -2 },
		{ type: STRUCTURE_ROAD,      dx: -1, dy: -2 },
		{ type: STRUCTURE_RAMPART,   dx: -1, dy: -2 },
		{ type: STRUCTURE_ROAD,      dx:  1, dy: -2 },
		{ type: STRUCTURE_RAMPART,   dx:  1, dy: -2 },
		{ type: STRUCTURE_ROAD,      dx:  2, dy: -2 },
		{ type: STRUCTURE_RAMPART,   dx:  2, dy: -2 },
		{ type: STRUCTURE_ROAD,      dx: -2, dy: -1 },
		{ type: STRUCTURE_RAMPART,   dx: -2, dy: -1 },
		{ type: STRUCTURE_ROAD,      dx:  0, dy: -1 },
		{ type: STRUCTURE_RAMPART,   dx:  0, dy: -1 },
		{ type: STRUCTURE_ROAD,      dx:  2, dy: -1 },
		{ type: STRUCTURE_RAMPART,   dx:  2, dy: -1 },
		{ type: STRUCTURE_ROAD,      dx: -1, dy:  0 },
		{ type: STRUCTURE_RAMPART,   dx: -1, dy:  0 },
		{ type: STRUCTURE_ROAD,      dx:  1, dy:  0 },
		{ type: STRUCTURE_RAMPART,   dx:  1, dy:  0 },
		{ type: STRUCTURE_ROAD,      dx: -2, dy:  1 },
		{ type: STRUCTURE_RAMPART,   dx: -2, dy:  1 },
		{ type: STRUCTURE_ROAD,      dx:  0, dy:  1 },
		{ type: STRUCTURE_RAMPART,   dx:  0, dy:  1 },
		{ type: STRUCTURE_ROAD,      dx:  2, dy:  1 },
		{ type: STRUCTURE_RAMPART,   dx:  2, dy:  1 },
		{ type: STRUCTURE_ROAD,      dx: -2, dy:  2 },
		{ type: STRUCTURE_RAMPART,   dx: -2, dy:  2 },
		{ type: STRUCTURE_ROAD,      dx: -1, dy:  2 },
		{ type: STRUCTURE_RAMPART,   dx: -1, dy:  2 },
		{ type: STRUCTURE_ROAD,      dx:  1, dy:  2 },
		{ type: STRUCTURE_RAMPART,   dx:  1, dy:  2 },
		{ type: STRUCTURE_ROAD,      dx:  2, dy:  2 },
		{ type: STRUCTURE_RAMPART,   dx:  2, dy:  2 },
		{ type: STRUCTURE_CONTAINER, dx:  2, dy:  0 },
		{ type: STRUCTURE_ROAD,      dx:  2, dy:  0 },
		{ type: STRUCTURE_RAMPART,   dx:  2, dy:  0 },
		{ type: STRUCTURE_CONTAINER, dx: -2, dy:  0 },
		{ type: STRUCTURE_ROAD,      dx: -2, dy:  0 },
		{ type: STRUCTURE_RAMPART,   dx: -2, dy:  0 },
		{ type: STRUCTURE_CONTAINER, dx:  0, dy:  2 },
		{ type: STRUCTURE_ROAD,      dx:  0, dy:  2 },
		{ type: STRUCTURE_RAMPART,   dx:  0, dy:  2 },
		{ type: STRUCTURE_CONTAINER, dx:  0, dy: -2 },
		{ type: STRUCTURE_ROAD,      dx:  0, dy: -2 },
		{ type: STRUCTURE_RAMPART,   dx:  0, dy: -2 },
	],
};

const bunker5: StrongholdTemplate = {
	name: 'bunker5',
	rewardLevel: 5,
	coreLevel: 5,
	structures: [
		{ type: STRUCTURE_RAMPART,   dx:  0, dy:  0 },
		{ type: STRUCTURE_TOWER,     dx:  1, dy:  1 },
		{ type: STRUCTURE_RAMPART,   dx:  1, dy:  1 },
		{ type: STRUCTURE_TOWER,     dx: -1, dy: -1 },
		{ type: STRUCTURE_RAMPART,   dx: -1, dy: -1 },
		{ type: STRUCTURE_TOWER,     dx: -1, dy:  1 },
		{ type: STRUCTURE_RAMPART,   dx: -1, dy:  1 },
		{ type: STRUCTURE_TOWER,     dx:  1, dy: -1 },
		{ type: STRUCTURE_RAMPART,   dx:  1, dy: -1 },
		{ type: STRUCTURE_TOWER,     dx:  0, dy: -2 },
		{ type: STRUCTURE_RAMPART,   dx:  0, dy: -2 },
		{ type: STRUCTURE_TOWER,     dx:  0, dy:  2 },
		{ type: STRUCTURE_RAMPART,   dx:  0, dy:  2 },
		{ type: STRUCTURE_ROAD,      dx: -2, dy: -3 },
		{ type: STRUCTURE_RAMPART,   dx: -2, dy: -3 },
		{ type: STRUCTURE_ROAD,      dx: -1, dy: -3 },
		{ type: STRUCTURE_RAMPART,   dx: -1, dy: -3 },
		{ type: STRUCTURE_ROAD,      dx:  0, dy: -3 },
		{ type: STRUCTURE_RAMPART,   dx:  0, dy: -3 },
		{ type: STRUCTURE_ROAD,      dx:  1, dy: -3 },
		{ type: STRUCTURE_RAMPART,   dx:  1, dy: -3 },
		{ type: STRUCTURE_ROAD,      dx:  2, dy: -3 },
		{ type: STRUCTURE_RAMPART,   dx:  2, dy: -3 },
		{ type: STRUCTURE_ROAD,      dx: -3, dy: -2 },
		{ type: STRUCTURE_RAMPART,   dx: -3, dy: -2 },
		{ type: STRUCTURE_ROAD,      dx: -1, dy: -2 },
		{ type: STRUCTURE_RAMPART,   dx: -1, dy: -2 },
		{ type: STRUCTURE_ROAD,      dx:  1, dy: -2 },
		{ type: STRUCTURE_RAMPART,   dx:  1, dy: -2 },
		{ type: STRUCTURE_ROAD,      dx:  3, dy: -2 },
		{ type: STRUCTURE_RAMPART,   dx:  3, dy: -2 },
		{ type: STRUCTURE_ROAD,      dx: -3, dy: -1 },
		{ type: STRUCTURE_RAMPART,   dx: -3, dy: -1 },
		{ type: STRUCTURE_ROAD,      dx: -2, dy: -1 },
		{ type: STRUCTURE_RAMPART,   dx: -2, dy: -1 },
		{ type: STRUCTURE_ROAD,      dx:  0, dy: -1 },
		{ type: STRUCTURE_RAMPART,   dx:  0, dy: -1 },
		{ type: STRUCTURE_ROAD,      dx:  2, dy: -1 },
		{ type: STRUCTURE_RAMPART,   dx:  2, dy: -1 },
		{ type: STRUCTURE_ROAD,      dx:  3, dy: -1 },
		{ type: STRUCTURE_RAMPART,   dx:  3, dy: -1 },
		{ type: STRUCTURE_ROAD,      dx: -3, dy:  0 },
		{ type: STRUCTURE_RAMPART,   dx: -3, dy:  0 },
		{ type: STRUCTURE_ROAD,      dx: -2, dy:  0 },
		{ type: STRUCTURE_RAMPART,   dx: -2, dy:  0 },
		{ type: STRUCTURE_ROAD,      dx: -1, dy:  0 },
		{ type: STRUCTURE_RAMPART,   dx: -1, dy:  0 },
		{ type: STRUCTURE_ROAD,      dx:  1, dy:  0 },
		{ type: STRUCTURE_RAMPART,   dx:  1, dy:  0 },
		{ type: STRUCTURE_ROAD,      dx:  2, dy:  0 },
		{ type: STRUCTURE_RAMPART,   dx:  2, dy:  0 },
		{ type: STRUCTURE_ROAD,      dx:  3, dy:  0 },
		{ type: STRUCTURE_RAMPART,   dx:  3, dy:  0 },
		{ type: STRUCTURE_ROAD,      dx: -3, dy:  1 },
		{ type: STRUCTURE_RAMPART,   dx: -3, dy:  1 },
		{ type: STRUCTURE_ROAD,      dx: -2, dy:  1 },
		{ type: STRUCTURE_RAMPART,   dx: -2, dy:  1 },
		{ type: STRUCTURE_ROAD,      dx:  0, dy:  1 },
		{ type: STRUCTURE_RAMPART,   dx:  0, dy:  1 },
		{ type: STRUCTURE_ROAD,      dx:  2, dy:  1 },
		{ type: STRUCTURE_RAMPART,   dx:  2, dy:  1 },
		{ type: STRUCTURE_ROAD,      dx:  3, dy:  1 },
		{ type: STRUCTURE_RAMPART,   dx:  3, dy:  1 },
		{ type: STRUCTURE_ROAD,      dx: -3, dy:  2 },
		{ type: STRUCTURE_RAMPART,   dx: -3, dy:  2 },
		{ type: STRUCTURE_ROAD,      dx: -1, dy:  2 },
		{ type: STRUCTURE_RAMPART,   dx: -1, dy:  2 },
		{ type: STRUCTURE_ROAD,      dx:  1, dy:  2 },
		{ type: STRUCTURE_RAMPART,   dx:  1, dy:  2 },
		{ type: STRUCTURE_ROAD,      dx:  3, dy:  2 },
		{ type: STRUCTURE_RAMPART,   dx:  3, dy:  2 },
		{ type: STRUCTURE_ROAD,      dx: -2, dy:  3 },
		{ type: STRUCTURE_RAMPART,   dx: -2, dy:  3 },
		{ type: STRUCTURE_ROAD,      dx: -1, dy:  3 },
		{ type: STRUCTURE_RAMPART,   dx: -1, dy:  3 },
		{ type: STRUCTURE_ROAD,      dx:  0, dy:  3 },
		{ type: STRUCTURE_RAMPART,   dx:  0, dy:  3 },
		{ type: STRUCTURE_ROAD,      dx:  1, dy:  3 },
		{ type: STRUCTURE_RAMPART,   dx:  1, dy:  3 },
		{ type: STRUCTURE_ROAD,      dx:  2, dy:  3 },
		{ type: STRUCTURE_RAMPART,   dx:  2, dy:  3 },
		{ type: STRUCTURE_CONTAINER, dx:  2, dy:  2 },
		{ type: STRUCTURE_ROAD,      dx:  2, dy:  2 },
		{ type: STRUCTURE_RAMPART,   dx:  2, dy:  2 },
		{ type: STRUCTURE_CONTAINER, dx: -2, dy: -2 },
		{ type: STRUCTURE_ROAD,      dx: -2, dy: -2 },
		{ type: STRUCTURE_RAMPART,   dx: -2, dy: -2 },
		{ type: STRUCTURE_CONTAINER, dx:  2, dy: -2 },
		{ type: STRUCTURE_ROAD,      dx:  2, dy: -2 },
		{ type: STRUCTURE_RAMPART,   dx:  2, dy: -2 },
		{ type: STRUCTURE_CONTAINER, dx: -2, dy:  2 },
		{ type: STRUCTURE_ROAD,      dx: -2, dy:  2 },
		{ type: STRUCTURE_RAMPART,   dx: -2, dy:  2 },
	],
};

export const strongholdTemplates: ReadonlyArray<StrongholdTemplate> = [
	bunker1, bunker2, bunker3, bunker4, bunker5,
];
