// Framework
export { code } from './code.js';
export type { PlayerCode } from './code.js';
export { RunPlayerError } from './errors.js';
export { test, describe, expect } from './fixture.js';
export { limitationGated } from './test-helpers.js';
export type { AdapterLimitation, AdapterLimitations } from './limitations.js';

// Adapter contract
export type {
	ScreepsOkAdapter, AdapterCapabilities, CapabilityName, PlayerReturnValue,
	ShardSpec, RoomSpec, PlayerSpec, TerrainSpec,
	CreepSpec, StructureSpec, SiteSpec, SourceSpec, MineralSpec,
	FlagSpec, TombstoneSpec, RuinSpec, DroppedResourceSpec,
	PowerCreepSpec, NukeSpec,
} from './adapter.js';
export type { SupportedFindConstant, NeutralFindSelector } from './find.js';
export { selectorFromFindConstant } from './find.js';

// Snapshots
export type {
	ObjectSnapshot, PosSnapshot,
	CreepSnapshot, StructureSnapshotBase, StructureSnapshot,
	ControllerSnapshot, SpawnSnapshot, LabSnapshot, TowerSnapshot,
	StorageSnapshot, LinkSnapshot, RampartSnapshot,
	TerminalSnapshot, FactorySnapshot, ExtensionSnapshot,
	ContainerSnapshot, ExtractorSnapshot, RoadSnapshot,
	NukerSnapshot, PowerSpawnSnapshot, WallSnapshot,
	SiteSnapshot, SourceSnapshot, MineralSnapshot,
	TombstoneSnapshot, RuinSnapshot, DroppedResourceSnapshot,
} from './snapshots/common.js';

// Screeps constants — for readable assertions in tests
export {
	// Large canonical tables (from @screeps/common)
	REACTIONS, BOOSTS, COMMODITIES, POWER_INFO, REACTION_TIME,
	// Return codes
	OK, ERR_NOT_OWNER, ERR_NO_PATH, ERR_NAME_EXISTS, ERR_BUSY,
	ERR_NOT_FOUND, ERR_NOT_ENOUGH_ENERGY, ERR_NOT_ENOUGH_RESOURCES,
	ERR_INVALID_TARGET, ERR_FULL, ERR_NOT_IN_RANGE, ERR_INVALID_ARGS,
	ERR_TIRED, ERR_NO_BODYPART, ERR_RCL_NOT_ENOUGH, ERR_GCL_NOT_ENOUGH,
	// Directions
	TOP, TOP_RIGHT, RIGHT, BOTTOM_RIGHT, BOTTOM, BOTTOM_LEFT, LEFT, TOP_LEFT,
	// Body parts
	MOVE, WORK, CARRY, ATTACK, RANGED_ATTACK, TOUGH, HEAL, CLAIM,
	// FIND constants
	FIND_CREEPS, FIND_MY_CREEPS, FIND_HOSTILE_CREEPS,
	FIND_SOURCES, FIND_SOURCES_ACTIVE, FIND_DROPPED_RESOURCES,
	FIND_STRUCTURES, FIND_MY_STRUCTURES, FIND_HOSTILE_STRUCTURES,
	FIND_FLAGS, FIND_CONSTRUCTION_SITES, FIND_MY_SPAWNS, FIND_HOSTILE_SPAWNS,
	FIND_MINERALS, FIND_NUKES, FIND_TOMBSTONES, FIND_DEPOSITS, FIND_RUINS,
	FIND_EXIT, FIND_EXIT_TOP, FIND_EXIT_RIGHT, FIND_EXIT_BOTTOM, FIND_EXIT_LEFT,
	// LOOK constants
	LOOK_CREEPS, LOOK_ENERGY, LOOK_RESOURCES, LOOK_SOURCES, LOOK_MINERALS,
	LOOK_STRUCTURES, LOOK_FLAGS, LOOK_CONSTRUCTION_SITES, LOOK_TERRAIN,
	LOOK_TOMBSTONES, LOOK_RUINS,
	// Structure types
	STRUCTURE_SPAWN, STRUCTURE_EXTENSION, STRUCTURE_ROAD, STRUCTURE_WALL,
	STRUCTURE_RAMPART, STRUCTURE_CONTROLLER, STRUCTURE_LINK, STRUCTURE_STORAGE,
	STRUCTURE_TOWER, STRUCTURE_OBSERVER, STRUCTURE_POWER_SPAWN,
	STRUCTURE_EXTRACTOR, STRUCTURE_LAB, STRUCTURE_TERMINAL,
	STRUCTURE_CONTAINER, STRUCTURE_NUKER, STRUCTURE_FACTORY, STRUCTURE_KEEPER_LAIR,
	STRUCTURE_POWER_BANK, STRUCTURE_INVADER_CORE,
	// Resources
	RESOURCE_ENERGY, RESOURCE_POWER, RESOURCE_GHODIUM,
	RESOURCE_SILICON, RESOURCE_METAL, RESOURCE_BIOMASS, RESOURCE_MIST,
	// Gameplay
	HARVEST_POWER, REPAIR_POWER, DISMANTLE_POWER, BUILD_POWER,
	ATTACK_POWER, RANGED_ATTACK_POWER, RANGED_ATTACK_DISTANCE_RATE,
	HEAL_POWER, RANGED_HEAL_POWER,
	BODYPART_HITS, TOWER_ENERGY_COST, UPGRADE_CONTROLLER_POWER,
	CREEP_CORPSE_RATE, TOMBSTONE_DECAY_PER_PART, DISMANTLE_COST, REPAIR_COST,
	CARRY_CAPACITY, ENERGY_REGEN_TIME,
	CREEP_LIFE_TIME, CREEP_CLAIM_LIFE_TIME, CREEP_PART_MAX_ENERGY, CREEP_SPAWN_TIME,
	MAX_CREEP_SIZE, SPAWN_RENEW_RATIO,
	BODYPART_COST, LINK_COOLDOWN, LINK_LOSS_RATIO,
	EXTRACTOR_COOLDOWN, HARVEST_MINERAL_POWER, OBSERVER_RANGE,
	TOWER_POWER_ATTACK, TOWER_POWER_HEAL, TOWER_POWER_REPAIR,
	TOWER_OPTIMAL_RANGE, TOWER_FALLOFF_RANGE, TOWER_FALLOFF,
	RAMPART_HITS_MAX,
	RAMPART_DECAY_AMOUNT, RAMPART_DECAY_TIME,
	// Construction cost
	CONSTRUCTION_COST,
	// Structure hits
	SPAWN_HITS, EXTENSION_HITS, ROAD_HITS, WALL_HITS, WALL_HITS_MAX,
	RAMPART_HITS, LINK_HITS, STORAGE_HITS, TOWER_HITS, OBSERVER_HITS,
	POWER_SPAWN_HITS, EXTRACTOR_HITS, LAB_HITS, TERMINAL_HITS,
	CONTAINER_HITS, NUKER_HITS, FACTORY_HITS,
	// Container decay
	// Dropped resource decay
	ENERGY_DECAY,
	// Container decay
	CONTAINER_DECAY, CONTAINER_DECAY_TIME, CONTAINER_DECAY_TIME_OWNED,
	// Road decay and wear
	ROAD_DECAY_AMOUNT, ROAD_DECAY_TIME, ROAD_WEAROUT, ROAD_WEAROUT_POWER_CREEP,
	CONSTRUCTION_COST_ROAD_SWAMP_RATIO, CONSTRUCTION_COST_ROAD_WALL_RATIO,
	// Source energy
	SOURCE_ENERGY_CAPACITY, SOURCE_ENERGY_NEUTRAL_CAPACITY, SOURCE_ENERGY_KEEPER_CAPACITY,
	// Ruin decay
	RUIN_DECAY, RUIN_DECAY_STRUCTURES,
	// Controller structure limits
	CONTROLLER_STRUCTURES,
	// Store capacities
	STORAGE_CAPACITY, TERMINAL_CAPACITY, TERMINAL_COOLDOWN, CONTAINER_CAPACITY, TOWER_CAPACITY,
	SPAWN_ENERGY_CAPACITY, EXTENSION_ENERGY_CAPACITY, LINK_CAPACITY,
	LAB_MINERAL_CAPACITY, LAB_ENERGY_CAPACITY,
	LAB_REACTION_AMOUNT, LAB_BOOST_MINERAL, LAB_BOOST_ENERGY,
	NUKER_ENERGY_CAPACITY, NUKER_GHODIUM_CAPACITY,
	POWER_SPAWN_ENERGY_CAPACITY, POWER_SPAWN_POWER_CAPACITY,
	FACTORY_CAPACITY,
	// Mineral density
	DENSITY_LOW, DENSITY_MODERATE, DENSITY_HIGH, DENSITY_ULTRA,
	MINERAL_DENSITY,
	// RawMemory segment limits
	MAX_ACTIVE_SEGMENTS, MAX_SEGMENT_COUNT, MAX_SEGMENT_SIZE,
	// Nuke
	NUKE_RANGE, NUKE_LAND_TIME, NUKE_DAMAGE,
	// Power constants
	PWR_OPERATE_TOWER, PWR_DISRUPT_TOWER, PWR_OPERATE_LAB, PWR_OPERATE_OBSERVER, PWR_OPERATE_FACTORY, PWR_OPERATE_TERMINAL,
	PWR_REGEN_SOURCE, PWR_REGEN_MINERAL,
	PWR_OPERATE_SPAWN, PWR_OPERATE_POWER, PWR_SHIELD, PWR_FORTIFY, PWR_DISRUPT_SOURCE, PWR_DISRUPT_TERMINAL,
	// Power creep / power bank
	POWER_LEVEL_MULTIPLY, POWER_LEVEL_POW,
	POWER_CREEP_LIFE_TIME, POWER_SPAWN_ENERGY_RATIO,
	POWER_BANK_HIT_BACK, POWER_BANK_CAPACITY_MAX, POWER_BANK_CAPACITY_MIN, POWER_BANK_DECAY, POWER_BANK_HITS,
	TOMBSTONE_DECAY_POWER_CREEP,
	// Construction site limit
	MAX_CONSTRUCTION_SITES,
	// Flags
	FLAGS_LIMIT, MARKET_ORDER_LIFE_TIME, COLOR_RED, COLOR_BLUE, COLOR_GREEN, COLOR_WHITE,
	// Safe mode
	SAFE_MODE_DURATION, SAFE_MODE_COOLDOWN, SAFE_MODE_COST,
	CONTROLLER_DOWNGRADE_SAFEMODE_THRESHOLD, CONTROLLER_DOWNGRADE, CONTROLLER_CLAIM_DOWNGRADE,
	CONTROLLER_LEVELS, CONTROLLER_RESERVE, CONTROLLER_RESERVE_MAX,
	CONTROLLER_MAX_UPGRADE_PER_TICK, CONTROLLER_ATTACK_BLOCKED_UPGRADE, CONTROLLER_NUKE_BLOCKED_UPGRADE,
	// Event log
	EVENT_ATTACK, EVENT_OBJECT_DESTROYED, EVENT_ATTACK_CONTROLLER,
	EVENT_BUILD, EVENT_HARVEST, EVENT_HEAL, EVENT_REPAIR,
	EVENT_RESERVE_CONTROLLER, EVENT_UPGRADE_CONTROLLER,
	EVENT_EXIT, EVENT_TRANSFER, EVENT_POWER,
	EVENT_ATTACK_TYPE_MELEE, EVENT_ATTACK_TYPE_RANGED,
	EVENT_ATTACK_TYPE_RANGED_MASS, EVENT_ATTACK_TYPE_DISMANTLE,
	EVENT_ATTACK_TYPE_HIT_BACK, EVENT_ATTACK_TYPE_NUKE,
	EVENT_HEAL_TYPE_MELEE, EVENT_HEAL_TYPE_RANGED,
	// Lab unboost
	LAB_UNBOOST_ENERGY, LAB_UNBOOST_MINERAL,
	// Terrain
	TERRAIN_PLAIN, TERRAIN_WALL, TERRAIN_SWAMP,
} from './constants.js';

// Helpers
export { body } from './helpers/body.js';
